apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80       # Exposed port
      targetPort: 80 # Port on the NGINX container
  type: LoadBalancer # Use LoadBalancer for external access, or ClusterIP for internal-only access
