apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  type: LoadBalancer  # Change this to NodePort or ClusterIP if needed
  ports:
    - port: 80        # The port that the service will expose
      targetPort: 80  # The port that the pod is listening on
  selector:
    app: react-app    # This should match the labels in the deployment
