apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\foto7\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: session-service
  name: session-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: session-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\foto7\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/boardgame-tracker-default: "true"
        io.kompose.service: session-service
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://board-game-tracker-sessions:K6wBiLWj9bQ3LgSUR501fQeah6JFQl3qrXHzqPxXVKRafKdpnWncpxAgGlYa7jSis1vc06SzasjhACDbS5c49A==@board-game-tracker-sessions.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@board-game-tracker-sessions@
            - name: INSIGHT_KEY
              value: InstrumentationKey=44e1cf59-dff6-4587-ae8b-6a974cd2acba;IngestionEndpoint=https://centralus-2.in.applicationinsights.azure.com/;LiveEndpoint=https://centralus.livediagnostics.monitor.azure.com/;ApplicationId=43049bad-b166-4005-af7c-e96b92e54deb
          image: fayv/boardgame-tracker-session-service
          name: session-service
          ports:
            - containerPort: 3003
              hostPort: 3003
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
